### ISSUE TITLE
Проблема с ncurses

### ISSUE THREAD

**Issue by flomazter** [mexxval/AcePHProxy#1]
При запуске прокси появляется ошибка
PHP Fatal error:  Call to undefined function ncurses_init() in /home/pi/AcePHProxy/class.ncurses_ui.php on line 40
Все зависимости установил и ncurses поставил 
Как можно исправить?

**Comment by irootssh** [comment]
Лол, нужно установить.

**Comment by flomazter** [comment]
что установить то?
 php5-dev и php-pear поставил 
pecl install ncurses установил, написало что все окай
но ошибка все равно есть

**Comment by irootssh** [comment]
В ошибке так и пишется, что интерпретатор хз что такое нкурсес. Вроде там еще дев нкурсес надо установить и вообще я на улице и пью пиво, гугли

**Comment by mexxval** [comment]
вероятно не подключен extension в php.ini
$ php -m | grep ncurses
ncurses

$ cat /etc/php5/cli/conf.d/30-ncurses.ini
extension=ncurses.so

**Comment by flomazter** [comment]
Эту проблему решил, погуглив и подключив ncurses в php.
