### ISSUE TITLE
Проигрывание торрент файлов и acelive потоков

### ISSUE THREAD

**Issue by flomazter** [mexxval/AcePHProxy#2]
Из инструкции не совсем понятно где должен лежать торрент файл, чтобы его можно было воспроизвести. Из кода понятно что это папка /STORAGE/FILES/ но вот где она должна быть не ясно, или в корне файловой системы или в папке со скриптом?
А так же как проигрывать acelive потоки с того же torrent-tv? или например если есть pid ссылка на видео как его проигрывать?
Разбирался в коде прокси, но так и не понял, тк мои познания в PHP очень малы

**Comment by mexxval** [comment]
дополнил вики способами запуска 
https://github.com/mexxval/AcePHProxy/wiki/Playlist
