### ISSUE TITLE
Add configuration option to disable ncurses GUI

### ISSUE THREAD

**Issue by garry222** [mexxval/AcePHProxy#7]

**Comment by mexxval** [comment]
а в конфиге секция UI не помогает?

**Comment by garry222** [comment]
не могу найти - не могли бы подсказать в каком файле эта настройка?

**Comment by mexxval** [comment]
res/.acePHProxy.settings

**Comment by garry222** [comment]
в моей версии нет такого файла. Насколько понимаю, это только что добавили. Спасибо!
