### ISSUE TITLE
Plugin type not found

### ISSUE THREAD

**Issue by garry222** [mexxval/AcePHProxy#9]
Скачал текущую версию. При попытке открыть одиночную трансляцию, типа 
http://192.168.10.10:8000/pid/262df5daa6bbf103621e2aed0d43db9baedffc58
в логе ace.log вижу тройное
Plugin type not found
Plugin type not found
Plugin type not found
и коннекта к acestream не происходит.

**Comment by mexxval** [comment]
https://github.com/mexxval/AcePHProxy/wiki/Playlist
